trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'Restore NuGet Packages'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Build Solution'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Run Unit Tests'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure para Estudantes Starter (fd82f79a-ef95-4dc8-9e03-de205d2efffc)'
    appType: 'webAppLinux'
    WebAppName: 'Auroque'
    deployToSlotOrASE: true
    ResourceGroupName: 'appsvc_linux_centralus'
    SlotName: 'production'
    package: '$(build.artifactStagingDirectory)/**/*.zip'
  displayName: 'Deploy to Azure Web App'

# Note on Changes
# 1. Updated task input for package deployment to 'package' from 'packageForLinux'.
# 2. Added 'displayName' to each task for better readability and management in logs.
